sudo: false

language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls

script: bash ./scripts/deploy.sh

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

env:
  global:
  - ENCRYPTION_LABEL: "f087f9824fa3"
  - COMMIT_AUTHOR_EMAIL: "kevin.pennarun@gmail.com"
